# Use the official PostgreSQL image as the base image
FROM postgres:13-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER root
ENV POSTGRES_PASSWORD root
ENV POSTGRES_DB craterDb

# Expose the PostgreSQL port
EXPOSE 5432