openapi: 3.0.0
info:
  title: Social Media API
  version: 1.0.0
  description: API for a social media platform similar to Twitter

paths:
  /users:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input

  /wags:
    post:
      summary: Create a wag 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '201':
          description: Wag created successfully
        '400':
          description: Invalid input

  /wags/{wagId}:
    put:
      summary: Edit a wag (premium users only)
      parameters:
        - in: path
          name: wagId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Wag updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - User not premium
