openapi: 3.0.0
info:
  title: Tailz API
  version: 1.0.0
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Bad request

  /api/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /api/posts:
    get:
      summary: Get user posts
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of user's posts
        '401':
          description: Unauthorized

    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                content:
                  type: string
      responses:
        '201':
          description: Post created successfully
        '401':
          description: Unauthorized

  /api/posts/{post_id}/comments:
    post:
      summary: Add a comment to a post
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                content:
                  type: string
      responses:
        '201':
          description: Comment added successfully
        '401':
          description: Unauthorized