// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package crater

import (
	"database/sql"
)

type DirectMessage struct {
	MessageID   int32
	SenderID    sql.NullString
	RecipientID sql.NullString
	Content     sql.NullString
	Timestamp   sql.NullTime
	IsRead      sql.NullBool
}

type ReWagz struct {
	RewagzID   int32
	UserID     sql.NullInt32
	OwnerWagID sql.NullInt32
	Timestamp  sql.NullTime
}

type User struct {
	UserID         int32
	Username       string
	Email          string
	PasswordHash   string
	FollowerCount  sql.NullInt32
	FollowCount    sql.NullInt32
	ProfilePicture sql.NullString
	Bio            sql.NullString
	JoinDate       sql.NullTime
	LastLogin      sql.NullTime
}

type Wagz struct {
	WagID       int32
	UserID      sql.NullInt32
	RewagzCount sql.NullInt32
	Likes       sql.NullInt32
	Content     string
	Timestamp   sql.NullTime
}
